### ISSUE TITLE
Microsoft Photos app download error

### ISSUE THREAD

**Issue by FaithfulObserver** [mjishnu/alt-app-installer#70]
I tried to download Microsoft Photos app (https://apps.microsoft.com/detail/9WZDNCRFJBH4) but got this error message:
IndexError: list index out of range

Here is the log content:
`[python logs] 
[11-12-2024 18:23:59]

Traceback (most recent call last):
  File "D:\alt-app-installer-2.6.9\app\utls.py", line 140, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\alt-app-installer-2.6.9\app\core.py", line 212, in <lambda>
    lambda **kwargs: asyncio.run(
                     ^^^^^^^^^^^^
  File "C:\Users\Test\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\Test\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Test\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "D:\alt-app-installer-2.6.9\app\modules\url_gen.py", line 455, in url_generator
    return await uwp_gen(session)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\alt-app-installer-2.6.9\app\modules\url_gen.py", line 295, in uwp_gen
    parse_names, main_file_name = parse_dict(
                                  ^^^^^^^^^^^
  File "D:\alt-app-installer-2.6.9\app\modules\url_gen.py", line 218, in parse_dict
    file_name = final_list[0]
                ~~~~~~~~~~^^^
IndexError: list index out of range
----------------------------------------------------------------------------------`

**Comment by mjishnu** [comment]
Thanks for reporting and sorry for delay in response. this was cause by a error in the xml file i have updated it you can either download the executable from the Realses page or go to internal -> data -> xml and replace WUIDRequest.xml (you can get the new one from repo [app -> data -> xml -> WUIDRequest.xml] )
